# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Server.exe doit être converti en Server.dll pour être exécuté sur Docker
COPY . .
RUN dotnet publish -c Release -o out

# Runtime
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app

RUN mkdir /app/logs

COPY --from=build /app/out .

EXPOSE 5000

ENTRYPOINT ["dotnet", "EasyLog.Server.dll"]

# Commandes à exécuter dans la console :
# docker build -t workshop-server .
# docker run -p 5000:5000 workshop-server